### ISSUE TITLE
Issues parsing 2d arrays

### ISSUE THREAD

**Issue by ferret-guy** [augustt198/latex2sympy#29]
This latex gives the following stack trace.
`A = \left( \begin{array} { l l l } { 2} & { 7} & { 3} \\ { 3} & { 5} & { 2} \\ { 9} & { 4} & { 1} \end{array} \right)`

```
Traceback (most recent call last):
  File "test - Copy.py", line 17, in <module>
    out = process_sympy(json.loads(r.text)['latex'])
  File "E:\Dropbox\Projects\mathpix\latex2sympy\process_latex.py", line 29, in process_sympy
    relation = parser.math().relation()
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 391, in math
    self.relation(0)
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 480, in relation
    self.relation(3)
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 456, in relation
    self.expr()
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 574, in expr
    self.additive(0)
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 630, in additive
    self.mp(0)
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 726, in mp
    self.unary()
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 925, in unary
    self.postfix()
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 1072, in postfix
    self.exp(0)
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 1474, in exp
    self.comp()
  File "E:\Dropbox\Projects\mathpix\latex2sympy\gen\PSParser.py", line 1691, in comp
    la_ = self._interp.adaptivePredict(self._input,20,self._ctx)
  File "C:\Python27\lib\site-packages\antlr4\atn\ParserATNSimulator.py", line 337, in adaptivePredict
    alt = self.execATN(dfa, s0, input, index, outerContext)
  File "C:\Python27\lib\site-packages\antlr4\atn\ParserATNSimulator.py", line 460, in execATN
    input.consume()
  File "C:\Python27\lib\site-packages\antlr4\BufferedTokenStream.py", line 97, in consume
    if self.sync(self.index + 1):
  File "C:\Python27\lib\site-packages\antlr4\BufferedTokenStream.py", line 109, in sync
    fetched = self.fetch(n)
  File "C:\Python27\lib\site-packages\antlr4\BufferedTokenStream.py", line 121, in fetch
    t = self.tokenSource.nextToken()
  File "C:\Python27\lib\site-packages\antlr4\Lexer.py", line 125, in nextToken
    self.notifyListeners(e)             # report error
  File "C:\Python27\lib\site-packages\antlr4\Lexer.py", line 280, in notifyListeners
    listener.syntaxError(self, None, self._tokenStartLine, self._tokenStartColumn, msg, e)
  File "C:\Python27\lib\site-packages\antlr4\error\ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "E:\Dropbox\Projects\mathpix\latex2sympy\process_latex.py", line 58, in syntaxError
    raise Exception(err)
Exception: I don't understand this
A = \left( \begin{array} { l l l } { 2} & { 7} & { 3} \\ { 3} & { 5} & { 2} \\ { 9} & { 4} & { 1} \end{array} \right)
```

**Comment by arturowin** [comment]
I've the same issue. Is someone fixed this problem?
